<?php

/**
 * BaseCheckList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                             $id                                   Type: integer, primary key
 * @property string                          $name                                 Type: string(255)
 * @property string                          $descriptor                           Type: clob
 * @property string                          $prefix                               Type: string(255)
 * @property int                             $threshold                            Type: integer
 * @property string                          $status                               Type: string(255)
 * @property string                          $versionAt                            Type: string
 * @property Doctrine_Collection|Criteria[]  $Criteria                             
 *  
 * @method int                               getId()                               Type: integer, primary key
 * @method string                            getName()                             Type: string(255)
 * @method string                            getDescriptor()                       Type: clob
 * @method string                            getPrefix()                           Type: string(255)
 * @method int                               getThreshold()                        Type: integer
 * @method string                            getStatus()                           Type: string(255)
 * @method string                            getVersionat()                        Type: string
 * @method Doctrine_Collection|Criteria[]    getCriteria()                         
 *  
 * @method CheckList                         setId(int $val)                       Type: integer, primary key
 * @method CheckList                         setName(string $val)                  Type: string(255)
 * @method CheckList                         setDescriptor(string $val)            Type: clob
 * @method CheckList                         setPrefix(string $val)                Type: string(255)
 * @method CheckList                         setThreshold(int $val)                Type: integer
 * @method CheckList                         setStatus(string $val)                Type: string(255)
 * @method CheckList                         setVersionat(string $val)             Type: string
 * @method CheckList                         setCriteria(Doctrine_Collection $val) 
 *  
 * @package    check-list
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCheckList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('check_list');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('descriptor', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('prefix', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('threshold', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('versionAt', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Criteria', array(
             'local' => 'id',
             'foreign' => 'check_list_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}