<?php

/**
 * BaseCheckList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property clob $descriptor
 * @property string $prefix
 * @property integer $threshold
 * @property string $status
 * @property string $versionAt
 * @property Doctrine_Collection $Criteria
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method clob                getDescriptor() Returns the current record's "descriptor" value
 * @method string              getPrefix()     Returns the current record's "prefix" value
 * @method integer             getThreshold()  Returns the current record's "threshold" value
 * @method string              getStatus()     Returns the current record's "status" value
 * @method string              getVersionAt()  Returns the current record's "versionAt" value
 * @method Doctrine_Collection getCriteria()   Returns the current record's "Criteria" collection
 * @method CheckList           setId()         Sets the current record's "id" value
 * @method CheckList           setName()       Sets the current record's "name" value
 * @method CheckList           setDescriptor() Sets the current record's "descriptor" value
 * @method CheckList           setPrefix()     Sets the current record's "prefix" value
 * @method CheckList           setThreshold()  Sets the current record's "threshold" value
 * @method CheckList           setStatus()     Sets the current record's "status" value
 * @method CheckList           setVersionAt()  Sets the current record's "versionAt" value
 * @method CheckList           setCriteria()   Sets the current record's "Criteria" collection
 * 
 * @package    check-list
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCheckList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('check_list');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('descriptor', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('prefix', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('threshold', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('versionAt', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Criteria', array(
             'local' => 'id',
             'foreign' => 'check_list_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}