<?php

/**
 * BaseCriteria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $check_list_id
 * @property double $weight
 * @property CheckList $CheckList
 * 
 * @method integer   getId()            Returns the current record's "id" value
 * @method string    getName()          Returns the current record's "name" value
 * @method integer   getCheckListId()   Returns the current record's "check_list_id" value
 * @method double    getWeight()        Returns the current record's "weight" value
 * @method CheckList getCheckList()     Returns the current record's "CheckList" value
 * @method Criteria  setId()            Sets the current record's "id" value
 * @method Criteria  setName()          Sets the current record's "name" value
 * @method Criteria  setCheckListId()   Sets the current record's "check_list_id" value
 * @method Criteria  setWeight()        Sets the current record's "weight" value
 * @method Criteria  setCheckList()     Sets the current record's "CheckList" value
 * 
 * @package    check-list
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCriteria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('criteria');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('check_list_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('weight', 'double', null, array(
             'type' => 'double',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CheckList', array(
             'local' => 'check_list_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}