<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2019/08/23 04:11:07

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=check-list',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
