<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2019/08/23 04:11:08
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionlistener' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwebdebugpaneldoctrine' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfformdoctrine' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecolumn' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'swift_doctrinespool' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinerecord' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineroute' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinebasetask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuilddbtask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildfilterstask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildmodeltask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildschematask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildsqltask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildtask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecleanmodelfilestask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinecompiletask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCompileTask.class.php',
  'sfdoctrineconfiguredatabasetask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinecreatemodeltables' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedatadumptask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinedataloadtask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinedqltask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedropdbtask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegenerateadmintask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemoduletask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrineinsertsqltask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinemigratetask' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sftesterdoctrine' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfvalidatordoctrinechoice' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinearraychoice' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineArrayChoice.class.php',
  'sfwidgetformdoctrinechoice' => 'D:/semillero/check-list/vendor/lexpress/symfony1/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'basechecklistformfilter' => 'D:/semillero/check-list/lib/filter/doctrine/base/BaseCheckListFormFilter.class.php',
  'baseformfilterdoctrine' => 'D:/semillero/check-list/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'checklistformfilter' => 'D:/semillero/check-list/lib/filter/doctrine/CheckListFormFilter.class.php',
  'baseform' => 'D:/semillero/check-list/lib/form/BaseForm.class.php',
  'basechecklistform' => 'D:/semillero/check-list/lib/form/doctrine/base/BaseCheckListForm.class.php',
  'baseformdoctrine' => 'D:/semillero/check-list/lib/form/doctrine/BaseFormDoctrine.class.php',
  'checklistform' => 'D:/semillero/check-list/lib/form/doctrine/CheckListForm.class.php',

  // project_model
  'basechecklist' => 'D:/semillero/check-list/lib/model/doctrine/base/BaseCheckList.class.php',
  'basecriteria' => 'D:/semillero/check-list/lib/model/doctrine/base/BaseCriteria.class.php',
  'checklist' => 'D:/semillero/check-list/lib/model/doctrine/CheckList.class.php',
  'checklisttable' => 'D:/semillero/check-list/lib/model/doctrine/CheckListTable.class.php',
  'criteria' => 'D:/semillero/check-list/lib/model/doctrine/Criteria.class.php',
  'criteriatable' => 'D:/semillero/check-list/lib/model/doctrine/CriteriaTable.class.php',

  // application
  'myuser' => 'D:/semillero/check-list/apps/frontend/lib/myUser.class.php',

  // modules
);
