<?php

/**
 * CheckListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CheckListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return CheckListTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CheckList');
    }
}