<?php

/**
 * CheckListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CheckListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return CheckListTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CheckList');
    }

    public static function sumWeightFromCriteria($checkListId) {
        $criteriaList = Doctrine_Query::create()->select('cl.id, cl.name, c.weight')->from('CheckList cl')->where('cl.id = ?',
            $checkListId)->leftJoin('cl.Criteria c')->fetchOne();

        var_dump($criteriaList);
        exit;
        foreach ($criteriaList as $criterion) {
            var_dump($criterion);
            exit;
        }
        exit;
    }
}