<?php

/**
 * CriteriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CriteriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return CriteriaTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Criteria');
    }

    public static function sumWeightByCheckList($checkListId) {
        $criteriaList = Doctrine_Query::create()->select('c.id, SUM(c.weight) as total')->from('Criteria c')->where('c.check_list_id = ?',
            $checkListId)->fetchArray();

        var_dump($criteriaList);
        exit;
        foreach ($criteriaList as $criterion) {
            var_dump($criterion);
            exit;
        }
        exit;
    }
}