<?php

/**
 * CheckList form.
 *
 * @package    check-list
 * @subpackage form
 * @author     Your name here
 * @version    SVN: $Id$
 */
class ResolverCheckListForm extends BaseCheckListForm
{
    public function configure()
    {
        // llamamos nuestro método que  incruta los sub formularios
        $this->embedStandardForm();


        // solo dejamos el nombre del sub formulario como campo habilitado
        $this->useFields(['standardList']);
    }

    /**
     * Este metodo  lo usaremos para embeber varios formularios de tipo checked_standard en el formulario principal
     * @throws sfException
     */
    private function embedStandardForm()
    {
        // creamos un formulario vacio que servira como contenedor
        $standardForm = new sfForm();
        // Obtenemos todos los criterios relacionados a la lista de chequeo
        $checkedStandardList = $this->getObject()->getCheckedStandards();

        $index = 0;
        // Iteramos por cada criterio
        /** @var  $checkedStandard  CheckedStandard */
        foreach ($checkedStandardList as $checkedStandard) {
            // creamos una instancia de un formulario de tipo checked_standardport cada iteracion del foreach
            // le pasamos como parametro el objecto de checked_standard para inicializar el formulario con los datos que tiene en base de datos
            $checkedStandardForm = new CheckedStandardForm($checkedStandard);

            // Incrustamos el formulario del criterio en el formulario que nos servira como contenedor
            $standardForm->embedForm($index, $checkedStandardForm);
            $index++;
        }

        // por ultimo incrustamos la lista de formulario en nuestro formulario principal con el nombre standardList
        $this->embedForm('standardList', $standardForm);

    }

    public function save($con = null)
    {

        return parent::save($con); // TODO: Change the autogenerated stub
    }
}
